### ISSUE TITLE
Python Notebooks -- removal of ``from __future__ import division``

### ISSUE THREAD

**Issue by mmcky** [QuantEcon/QuantEcon.applications#12]
Currently there are a number of notebooks with

`from __future__ import division`

this allows those notebooks to behave properly in python2.7. Given the recent migration to support python3.5 we can now remove these from notebooks.

**Comment by jstac** [comment]
Thanks.  That was in the back of my mind but I kept forgetting to mention it.  Would you mind to grep it?
