### ISSUE TITLE
Bug? in lakemodel_example.py

### ISSUE THREAD

**Issue by oyamad** [QuantEcon/QuantEcon.applications#14]
(I am writing this here since the [lecture page](http://quant-econ.net/py/lake_model.html#implementation) is linked to files in this repo.)

Is `w = (w[1:] + w[:1])/2` on [this line](https://github.com/QuantEcon/QuantEcon.applications/blob/master/lake_model/lakemodel_example.py#L106) meant to be `w = (w[1:] + w[:-1])/2`? With the latter, the optimal unemployment benefit gets more than doubled.

**Comment by oyamad** [comment]
And one more:

What does `alpha_q = (1-(1-alpha)**3)` on [this line](https://github.com/QuantEcon/QuantEcon.applications/blob/master/lake_model/lakemodel_example.py#L96) mean? If `alpha = 0.013` is the separation probability for 1/3 periods, then `alpha_q` is the separation probability for 1 period. Is it what it is supposed to mean?

**Comment by oyamad** [comment]
Answer from the author:

* It is meant to be `w = (w[1:] + w[:-1])/2`.
* `alpha` is the monthly rate and `alpha_q` is quarterly.

**Comment by jstac** [comment]
@oyamad Thanks for picking up these issues.  I've made the changes you flagged --- please see [this line](https://github.com/QuantEcon/QuantEcon.applications/blob/master/lake_model/lakemodel_example.py#L96) and [this line](https://github.com/QuantEcon/QuantEcon.applications/blob/master/lake_model/lakemodel_example.py#L106).  If I've done it correctly please go ahead and close.

**Comment by oyamad** [comment]
@jstac Thanks!
Closing.

**Comment by oyamad** [comment]
One more thing:

For [this line](https://github.com/QuantEcon/QuantEcon.applications/blob/master/lake_model/lakemodel_example.py#L112), the figures should look nice if it is replaced with, e.g., `np.linspace(5, 135, 25)`; see the figures in [this notebook](http://nbviewer.ipython.org/github/QuantEcon/QuantEcon.notebooks/blob/ddp/discrete_dp/ddp_ex_job_search_py.ipynb).

**Comment by oyamad** [comment]
As pointed out by https://groups.google.com/forum/#!topic/quantecon/okWAS-YjTwE ("2nd"), I suspect the lecture page has not been updated.

**Comment by jstac** [comment]
@oyamad Thanks for the comments.  I've just fixed this, adopting your suggestion for the linspace range.  The changes will go live soon.
