### ISSUE TITLE
the function "meshgrid" can not work

### ISSUE THREAD

**Issue by cnzxcxt1** [QuantEcon/QuantEcon.applications#18]
hello,
when I tried to plot the 3D plots with the function meshgrid, I came across some errors.

**Comment by jstac** [comment]
@cnzxcxt1 Thanks for your feedback.  Can you please tell us which file you tried to run, what your error message was and what version of Python you are using.

**Comment by guanlong1989** [comment]
When I run this code, there is 
LoadError: MethodError: `meshgrid` has no method matching meshgrid(::LinSpace{Float64}, ::LinSpace{Float64}). 

The problem might be derived from line 9 " Quick meshgrid function " : 
"
meshgrid(x::Vector, y::Vector) = (repmat(x, 1, length(y))',
                                  repmat(y, 1, length(x)))
"
which is not consistent with 
"
x_grid = linspace(-1.5, 2.9, 100)
y_grid = linspace(-3.1, 1.7, 100)
X, Y = meshgrid(x_grid, y_grid) .
"
Thus, regarding defining "meshgrid function", this one

meshgrid(x::LinSpace, y::LinSpace) = (repmat(x, 1, length(y))',
                                  repmat(y, 1, length(x)))
works.

**Comment by jstac** [comment]
@guanlong1989 Thanks for your comment.  Line 9 of which file?

Is the issue with this code?

http://quant-econ.net/jl/julia_libraries.html#d-plots

It should run fine with the latest version of QuantEcon.jl.  Note that `meshgrid` now expects `AbstractVector`.

https://github.com/QuantEcon/QuantEcon.jl/blob/master/src/util.jl#L9

Please let me know if this addresses the problem so that I can close the issue.

**Comment by guanlong1989** [comment]
Sorry, I mean that the Line 9 in the file named "gaussian_contours.jl" in Kalman folder.

https://github.com/QuantEcon/QuantEcon.applications/blob/master/kalman/gaussian_contours.jl

Also, you are right, meshgrid now expects AbstractVector. Thus, please replace the Vector with AbstractVector for meshgrid function.

Many thanks.

**Comment by jstac** [comment]
I understand the problem now.  Thanks @guanlong1989.  I'm going to close this and open a separate issue.
