### ISSUE TITLE
Missing Julia solution notebook in lucas_model

### ISSUE THREAD

**Issue by jstac** [QuantEcon/QuantEcon.applications#2]
Only a Python solution notebook exists

https://github.com/QuantEcon/QuantEcon.applications/tree/master/lucas_model

**Comment by mmcky** [comment]
This is flagging a broken link on the ``julia`` side of the side. I will remove the solutions notebook from the Julia page for now.

**Comment by jstac** [comment]
@

**Comment by jstac** [comment]
@mmcky Thanks.  I'll try to fix this today.

**Comment by jstac** [comment]
Fixed.

http://nbviewer.jupyter.org/github/QuantEcon/QuantEcon.applications/blob/master/lucas_model/lucas_asset_solutions_jl.ipynb
