### ISSUE TITLE
finite_mc_solutions_jl.ipynb is broken

### ISSUE THREAD

**Issue by jstac** [QuantEcon/QuantEcon.applications#30]
The code doesn't run.  I think it's old syntax for simulating from an MC.

Also, the link at the very bottom is broken.  It should point to the Julia QuantEcon code for Tauchen's method.

Ref: http://nbviewer.jupyter.org/github/QuantEcon/QuantEcon.applications/blob/master/finite_markov/finite_mc_solutions_jl.ipynb

**Comment by oyamad** [comment]
The broken link at the bottom has been fixed by #26.
I am going to fix `mc_sample_path` now.

**Comment by oyamad** [comment]
Maybe better to say "The exercise is to write a function ... that returns a `MarkovChain` instance ..." (in both the jl and py versions)?

**Comment by jstac** [comment]
@oyamad Thanks for the the suggestion.  I made the change and I'll upload it soon.
