### ISSUE TITLE
On julia_arrays_solutions.ipynb

### ISSUE THREAD

**Issue by oyamad** [QuantEcon/QuantEcon.applications#32]
Some comments on [julia_arrays_solutions.ipynb](https://github.com/QuantEcon/QuantEcon.applications/blob/master/julia_arrays/julia_arrays_solutions.ipynb):

1.
On cell [3], I am afraid `eigmax(A)` is not appropriate for checking that "all eigenvalues of A lie inside the unit disc": one reason is that [`eigmax`](https://github.com/JuliaLang/julia/blob/master/base/linalg/eigen.jl#L105-L111) does not work throwing an error if the matrix `A` has complex eigenvalues:

```jl
julia> A = [0.5 0.5; -0.5 0.5]
2x2 Array{Float64,2}:
  0.5  0.5
 -0.5  0.5

julia> eigmax(A)
ERROR: DomainError:
```

It may be better to replace it with

```jl
maximum(abs(eigvals(A)))
```

```jl
maximum(abs(eigvals(A))) < 1
```

```jl
all(abs(eigvals(A)) .< 1)
```

or one with `abs2` in place of `abs`.

2.
If it is not the case that the eigenvalues of `A` are smaller than one in absolute value, then the current implementation of `compute_asymptotic_var` will go in infinite loops. For safety, I would add an option `iter_max`.

3.
To verify the claim "the sequence {S_t} converges to a unique limit S", it may be worthwhile to add an option `S_0` to `compute_asymptotic_var`.

**Comment by jstac** [comment]
@oyamad Many thanks.  

It's disappointing that `eigmax` doesn't work when `A` has complex eigenvalues.

I adopted your suggestions:

http://nbviewer.jupyter.org/github/QuantEcon/QuantEcon.applications/blob/master/julia_arrays/julia_arrays_solutions.ipynb
