### ISSUE TITLE
plotting in Julia

### ISSUE THREAD

**Issue by jstac** [QuantEcon/QuantEcon.applications#47]
@spencerlyon2 
@cc7768 
@albep 
@vgregory757 
@guanlong1989 
@oyamad 

I notice that @albep has changed [jv_test.jl](https://github.com/QuantEcon/QuantEcon.applications/blob/master/jv/jv_test.jl) to use PlotlyJS, so perhaps now is a good time to discuss how we're going to coordinate on plotting in Julia.

(Aside: I broke up the long lines in the plot commands of the [previous commit](https://github.com/QuantEcon/QuantEcon.applications/blob/1999e5db788ab68d8e920d5656a4fea031e27969/jv/jv_test.jl) because I prefer that we stick to lines of max length 80 characters)

I like PlotlyJS but installation is not always trivial. My instinct would be to go with [Plots](https://github.com/tbreloff/Plots.jl).

It seems to me that we could now systematically switch to Plots.  It appears to be stable and I think it's here to stay.

Comments?

**Comment by albep** [comment]
Thanks @jstac. I've never used that package, but I'd be happy to switch to it. (I thought that PlotlyJS installation had been made easier recently, @spencerlyon2 ?)

**Comment by spencerlyon2** [comment]
So I have quite a bit of experience with Plots.jl. It is a unique package in the plotting world in that it simply a frontend into many different plotting libraries. The idea is that you can use the same API and swap out different backends. This means you can write your plotting code, and then choose to have PyPlot.jl, PlotlyJS.jl, Gadfly.jl (still works -- although it has been deprecated as a backend for Plots), GR.jl, and others actually render the plots.

One thing is that is is being actively developed right now, so I don't know that I'd call it stable. I definitely agree that it is here to stay.

I think that we should use Plots.jl and maybe make a note that we like the plotlyjs backend for Plots. We can actually do some pretty cool things once we adopt the Plots ecosystem, which makes me even more excited to go down this path.

cc @tbreloff

**Comment by tbreloff** [comment]
Of course you should use Plots.  👍   I'm still actively developing pieces of Plots, but I wouldn't expect tons of breaking changes going forward.  PlotlyJS is pretty well supported, in fact I even solved the `:shape` type today: https://github.com/tbreloff/Plots.jl/issues/385#issuecomment-231545968

Stop by gitter if you have any questions.

**Comment by jstac** [comment]
Sounds good to me.  We can put in an updated and more extensive discussion of plotting in Julia here:

http://quant-econ.net/jl/julia_libraries.html

Or in fact we could add a separate lecture that provides multiple examples, perhaps replicating the plots here:

http://quant-econ.net/py/matplotlib.html

As well as recommending PlotlyJS, we can discuss different back-ends and let people try their luck.   We can run them through the options, and if one doesn't work for them on a given platform another one might.

**Comment by albep** [comment]
This sounds great, happy to start using Plots.jl. I can update `jv_test.jl` to reflect that

**Comment by jstac** [comment]
@albep Sounds good.  I think everyone has weighed in now so you can go ahead.  

I'll try to write up an exposition of Plots.jl as discussed above in the next few weeks.

**Comment by tbreloff** [comment]
@jstac Please review the Plots documentation first, as I have a lot of info there.  If you come up with a more streamlined "quick tutorial", I'd love to link to it from my docs (with permission).  Let me know if I can help with anything... gitter is the easiest forum for questions.

**Comment by jstac** [comment]
@tbreloff Thanks.  I'll read the documentation carefully and then write my own quick tutorial with lots of examples.  I'll also link to your tutorial and documentation.  

I'll let you know when I'm done.

We get a lot of traffic at the moment so hopefully we can help coordinate people on your package.

**Comment by datnamer** [comment]
@jstac out of curiosity, what does the python vs julia quant econ traffic look like?

**Comment by jstac** [comment]
@datnamer Pretty similar, actually.  

http://chickenlegs.org/awstats/awstats.pl?config=quant-econ.net

The Python PDF is downloaded twice as often, but for the web site the intro Julia lectures get more visitors than their Python counterparts.  

Total monthly unique visitors is around 22K.

**Comment by jstac** [comment]
@vgregory757 Thanks for agreeing to redo the plots!  As well as the code that produces plots in Julia in the *.jl files in this repo, which you can probably search for with grep, there's also the code that produces plots in this lecture:

http://quant-econ.net/jl/estspec.html#calculation

and this lecture:

http://quant-econ.net/jl/julia_by_example.html

And there's code for plots in the solution notebooks.  See, e.g., 

http://nbviewer.jupyter.org/github/QuantEcon/QuantEcon.applications/blob/master/career/career_solutions_jl.ipynb

It's a big job -- we really appreciate your help.

**Comment by albep** [comment]
Thanks @vgregory757 . I'm happy to help you as I go through the issues in this repo and work on notebooks with plots. @jstac, would you like to agree on a unique backend across all QuantEcon, or we can use different backends for different plots at least in the notebooks?

**Comment by jstac** [comment]
Good question.  

I'll certainly introduce multiple back ends in the lecture I write for Plots.jl but perhaps it's a good idea to coordinate on one back end for the majority of the plots we write.

My concern is that the quality is high and the code works for almost all users with a minimum of hassles.

@spencerlyon2 
@tbreloff 

Do you have opinions?

**Comment by tbreloff** [comment]
> code works for almost all users with a minimum of hassles

I wish there was a clear winner here.  Each has pros and cons.  Luckily you shouldn't need to focus on backends too much.  Just point them to [the docs](https://juliaplots.github.io/backends/) and let them decide.

**Comment by spencerlyon2** [comment]
The absolute minimum hassle backend would be the `plotly` backend (not `plotlyjs`). That is bundled with Plots.jl and doesn't require any packages to be installed. 

However, as @tbreloff says I don't think we need to worry about introducing multiple backends. We can mention that it works with more than one and then point them to the docs where @tbreloff  has given a pretty good description of the pros/cons of each backend

**Comment by vgregory757** [comment]
Thanks @albep . I started working with the `plotlyjs` backend and so far it works well for me, except for latex labeling. Does it support adding latex labels to plots? I tried the solution [here](https://github.com/tbreloff/Plots.jl/issues/359) which does work with the `pyplot` backend.

**Comment by spencerlyon2** [comment]
@vgregory757 latex is totally supported by plotly, I  just haven't hooked it up to plotlyjs yet. This is good motivation for me to do it :)

If you can give me a day or two I'll have it ready to go. If plotlyjs has been working well for you, you can keep working with that one!

**Comment by vgregory757** [comment]
@spencerlyon2 thanks, sounds great. I'll go back to that once you're done. I'll let you know if I run into any other issues.

**Comment by albep** [comment]
@vgregory757 happy to keep using `plotlyjs` backend, so we can coordinate on that

**Comment by jstac** [comment]
@spencerlyon2 I'm hoping to write up the plotting lecture today.  LaTeX integration is a must-have.  How are you going with LaTeX and `plotlyjs`?  I know you have a lot on so how about I write it up with a `pyplot` back-end for now.  Once you have LaTeX working we can swap to your back-end.

**Comment by spencerlyon2** [comment]
Hey @jstac not a problem. Feel free to start with whatever backend works.

**Comment by spencerlyon2** [comment]
Hey @jstac sorry, this comment got lost in my inbox.

I currently have latex working in the electron frontend, but haven't gotten things configured properly within the notebook. I'll update once I've had a chance to figure it all out
