### ISSUE TITLE
update Markov chain code here and in lectures

### ISSUE THREAD

**Issue by jstac** [QuantEcon/QuantEcon.applications#51]
Once a new version of QuantEcon.jl is released to bring it up to date with

https://github.com/QuantEcon/QuantEcon.jl/pull/115

the code in this repo needs to be changed accordingly.  We will also need to adjust the code in 

http://quant-econ.net/jl/finite_markov.html

and perhaps some other places.  I'll open an issue there too.

**Comment by oyamad** [comment]
What about the python version?

* `mc_compute_stationary` is used in finite_markov/mc_convergence_plot.py and finite_markov/finite_mc_solutions_py.ipynb.
* `mc_sample_path` is also used in several .py files.

**Comment by jstac** [comment]
@oyamad Thanks for the reminders.

I've made all these changes.  As far as I know I updated all instances.
