### ISSUE TITLE
Optimizing the McCall model in Julia

### ISSUE THREAD

**Issue by vgregory757** [QuantEcon/QuantEcon.applications#61]
The Julia version of the LakeModel code with the endogenous job-finding rate, submitted in #60, is very slow at finding the market-clearing tax rate, given a level of unemployment benefits in `find_balanced_budget_tax` (for details on the problem see [here](http://quant-econ.net/py/lake_model.html#endogenous-job-finding-rate)). This function employs a root-finding algorithm. The profiler finds that most of the time is spent on repeatedly evaluating the functions in `mccall_bellman_iteration.jl` (particularly `update_bellman!`). Does anyone have any suggestions on how to improve speed here? Perhaps some type declarations should be added to the functions. Or maybe parallelizing the VFI?

**Comment by jstac** [comment]
If types are inferred correctly we should be able to get it comparable to the jitted Python code without parallelization...  That would be fast enough.

Of course we should cover parallelization itself in a lecture very soon.  Lots of people ask about it.

**Comment by spencerlyon2** [comment]
There are a few small changes I made to help Julia infer types. I'll open a PR. 

Run time on the `solve_mccall_model` function went from 0.05 to 0.001

**Comment by jstac** [comment]
@spencerlyon2 Thanks!  Just what we needed.  And I learned a lot from reading your PR, which is really valuable for me.

**Comment by spencerlyon2** [comment]
Excellent, glad you could learn from it!
