### ISSUE TITLE
JV improvement

### ISSUE THREAD

**Issue by jstac** [QuantEcon/QuantEcon.applications#81]
Can "# NOTE: only brute-force approach is available in bellman operator. Waiting on a simple constrained optimizer " be addressed now in 

https://github.com/QuantEcon/QuantEcon.applications/blob/master/jv/jv.jl

**Comment by sglyon** [comment]
I think this is the latest: https://github.com/JuliaNLSolvers/Optim.jl/pull/303

So no, not quite yet
